
# Travis task settings for repository testing
# Documentation:
# https://docs.travis-ci.com/user/customizing-the-build

warnings_are_errors: true

language: ruby
rvm:
  - 2.2
before_install:
  - nvm i node
before_script:
  - npm i
script:
  - npm run lint
  - npm run build
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
